backend/urls.py
#
#  Copyright (C) 2010 GSyC/LibreSoft, Universidad Rey Juan Carlos
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
#    Author : Roberto Calvo Palomino <rocapal_at_librsoft_dot_es>        
#


from django.conf.urls.defaults import patterns, url
from django.views.generic.simple import direct_to_template

from views import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns(
        '',

	(r'^$', init),
    (r'^login/$', login),
    
    (r'^home/$', home),
    
    (r'^layers/$', layers),
    (r'^layers/(?P<layer_id>[1-9][0-9]*)/$', get_layers_content), 
    (r'^layers/delete/$', layers_delete),    
    
    (r'^layers/(?P<layer_id>[1-9][0-9]*)/node/(?P<node_id>[1-9][0-9]*)/delete/$', delete_node), 
    
    (r'^contents/$', contents),
    (r'content/note/create/$', note_create),
    (r'content/photo/create/$', photo_create),
    (r'content/sound/create/$', sound_create),
    
)

urls.py
from django.conf.urls import patterns, include, url
import os
from os.path import join

from settings import MEDIA_ROOT, APPS_DIR, BASEDIR, INFOMEDIA_ROOT

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lgs.views.home', name='home'),
    # url(r'^lgs/', include('lgs.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^version/', 'social.rest.views.version',),
    url(r'^social/',include('social.rest.urls'),),
    url(r'^backend/',include('backend.urls'),),
    url(r'^site_media/images/photos','social.rest.views.forbbiden_photo',),
    url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':MEDIA_ROOT}),
    url(r'^agregador/', include('agregador.urls'),),
    url(r'^infomedia/(?P<path>.*)$','django.views.static.serve',{'document_root':INFOMEDIA_ROOT}),
)


def look_up_apps():
    apps_dir = join(BASEDIR,APPS_DIR)
    print apps_dir
    dirs = os.listdir(apps_dir)
    pat = urlpatterns
    for dir in dirs:
        if os.path.isdir(join(apps_dir,dir)) and dir[0] not in ('.','_'):
            urls=r'^%s/' % dir
            urls_file='%s.%s.urls' % (APPS_DIR,dir)
            pat= pat + patterns('',(urls,include(urls_file)))
    return pat




try:
    urlpatterns= look_up_apps()
except:
    pass

social/rest/forms.py
#
#  Copyright (C) 2009 GSyC/LibreSoft
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
#    Author : Jose Antonio Santos Cadenas <jcaden __at__ gsyc __dot__ es>
#


from django.utils.translation import ugettext_lazy as _, ugettext
from django import forms

from social.core import config

class LoginForm (forms.Form):
        username = forms.CharField(label=_('username'))
        password = forms.CharField(label='password', widget = forms.PasswordInput)
        user = None   # allow access to user object

        def clean(self):
            # only do further checks if the rest was valid
            if self._errors: return

            from django.contrib.auth import authenticate
            user = authenticate(username=self.data['username'],
                                password=self.data['password'])
            if user is not None:
                if user.is_active:
                    self.user = user
                else:
                    raise forms.ValidationError(ugettext(
                        'This account is currently inactive. Please contact '
                        'the administrator if you believe this to be in error.'))
            else:
                raise forms.ValidationError(ugettext(
                    'The username and password you specified are not valid.'))
                
        def login(self, request):
            from django.contrib.auth import login
            if self.is_valid():
                login(request, self.user)
                return self.user.id
            return False

class PhotoForm(forms.Form):
    name = forms.CharField(max_length=30, required=True, label=_('Image name'))
    photo = forms.Field(widget=forms.FileInput,
                        required=False, 
                        label=_('Photo'), 
                        help_text=_('Upload an image (max %s kilobytes)' % config.MAX_PHOTO_UPLOAD_SIZE))

class ComparePhotoForm(forms.Form):
    name = forms.CharField(max_length=30, required=True, label=_('Image name'))
    photo = forms.Field(widget=forms.FileInput,
                        required=False, 
                        label=_('Photo'), 
                        help_text=_('Upload an image (max %s kilobytes)' % config.MAX_PHOTO_UPLOAD_SIZE))


class SoundForm(forms.Form):
    name = forms.CharField(max_length=30, required=True, label=_('Sound file name'))
    sound = forms.Field(widget=forms.FileInput,
                        required=False, 
                        label=_('Sound'), 
                        help_text=_('Upload a sound file'))
    
class VideoForm(forms.Form):
    name = forms.CharField(max_length=30, required=True, label=_('Video file name'))
    video = forms.Field(widget=forms.FileInput,
                        required=False, 
                        label=_('Video'), 
                        help_text=_('Upload a video file(max %s kilobytes)' % config.MAX_VIDEO_UPLOAD_SIZE))
 
class IconForm(forms.Form):
    name = forms.CharField(max_length=30, required=True, label=_('Icon name'))
    icon = forms.Field(widget=forms.FileInput,
                        required=False, 
                        label=_('Icon'), 
                        help_text=_('Upload an image (max %s kilobytes)' % config.MAX_ICON_UPLOAD_SIZE))  

backend/views.py
#
#  Copyright (C) 2010 GSyC/LibreSoft, Universidad Rey Juan Carlos
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
#    Author : Roberto Calvo Palomino <rocapal_at_librsoft_dot_es>        
#

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib import auth
from django.template import Context
from social.layers.layers_manager import *
from social.rest.layers import create_layer, delete_layer, request_layer
from social.rest.notes import note_upload
from social.rest.photos import photo_upload
from social.rest.sounds import sound_upload
from social.rest.views import node_delete

from social.core.api_layer import get_layer

def init (request):

    con = Context({ 'mensaje'   : 'hola', })

    html = render_to_response ( 'backend/login/index.html', con )
    return HttpResponse( html)


def login(request):
    
    if request.method == 'POST':
        password =  request.POST.get('password', '')
        username =  request.POST.get('username', '')
        
        user = auth.authenticate( username=username , password=password)
        
        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect('/backend/home')
        else:
            con =  Context({ 'message' : "Error de autenticacion" , })
            return render_to_response('backend/login/', con )
        
    html = render_to_response ('backend/login/index.html')
    return HttpResponse( html)

        
def home (request):
    
    if not request.user.is_authenticated():
        return HttpResponseRedirect('backend/login/')
    
    html = render_to_response ('backend/home.html')
    return HttpResponse( html)


def layers (request):
    
    if not request.user.is_authenticated():
        return HttpResponseRedirect('backend/layers/')    
    
    msg = ""
    
    if request.method == 'POST':
        data = create_layer(request)
    
    success, results = layers_list (request.user,True)
    
    
    con =  Context({ 'url_create_layer': '/backend/layers/',
                     'results' : results ,
                     'msg' : msg })
    
    html = render_to_response ('backend/layers.html', con )
    return HttpResponse( html)

def get_layers_content (request, layer_id):
    
    options = request.GET.copy()
    options["user"] = request.user
    options["layer_id"] = layer_id
    options["latitude"]=0.0
    options["longitude"]=0.0
    options["radius"]=0.0
    options["category"]="0"
    options["elems"]=10000
    
    success, response = layers_search(layer_id, "", options)
   
    print response
    print type (response[0].position)
    
    con =  Context({ 'url_create_layer': '/backend/layers/',
                     'list' : response,
                     'layer_id' : layer_id,
                     'msg' : "" })
    
    html = render_to_response ('backend/node_list.html', con )
    return HttpResponse( html)
    
def layers_delete (request):
    
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/backend/layers/') 
    
    
    if request.method == 'POST':
        
        idInt = int(request.POST["id"])
        res = delete_layer(request,idInt)
    
    return HttpResponseRedirect('/backend/layers/') 
    
    
        
def contents (request):
    
    
    if not request.user.is_authenticated():
        return HttpResponseRedirect('backend/contents/')    
    
    success, results = layers_list (request.user,True)          
    
    msg=""
    con =  Context({ 'results' : results ,
                     'msg' : msg })
    html = render_to_response ('backend/contents.html', con )
    return HttpResponse(html)


def list_nodes (request):
    
    if not request.user.is_authenticated():
        return HttpResponseRedirect('backend/contents/')
    
    con =  Context({ 'layer' : layer ,
                     'msg' : msg })
    
    html = render_to_response ('backend/contents.html', con )
    return HttpResponse(html)
    
def delete_node (request, layer_id, node_id):
    
    result = node_delete(request,layer_id,node_id)
    print result
    
    return get_layers_content(request, layer_id)
    
def note_create (request):
    
    if not request.user.is_authenticated():
        return HttpResponseRedirect('backend/contents/')
    
    res = note_upload(request, int(request.POST["layer"]) )
    success, results = layers_list (request.user,True)          
    
    print res
    
    msg=""
    con =  Context({ 'results' : results ,
                     'msg' : msg })
    html = render_to_response ('backend/contents.html', con )
    return HttpResponse(html)

    
def photo_create (request):
    
    if not request.user.is_authenticated():
        return HttpResponseRedirect('backend/contents/')
    
    res = photo_upload(request, int(request.POST["layer"]) )
    success, results = layers_list (request.user,True)          
    
    print res
    
    msg=""
    con =  Context({ 'results' : results ,
                     'msg' : msg })
    html = render_to_response ('backend/contents.html', con )
    return HttpResponse(html)


def sound_create (request):
    
    if not request.user.is_authenticated():
        return HttpResponseRedirect('backend/contents/')
    
    res = sound_upload(request, int(request.POST["layer"]) )
    success, results = layers_list (request.user,True)          
    
    print res
    
    msg=""
    con =  Context({ 'results' : results ,
                     'msg' : msg })
    html = render_to_response ('backend/contents.html', con )
    return HttpResponse(html)    

templates/backend/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>LibreGeoSocial Backend</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" href="/infomedia/css/menu-style.css" type="text/css" />
<link rel="stylesheet" type="text/css" href="/infomedia/css/table-style.css" />

</head>
<body>

<div id="wrap" >

	<div id="dolphincontainer">
	  <div id="dolphinnav">
	    <ul>
	      <li><a href="/backend/home"><span>HOME</span></a></li>
	      <li><a href="/backend/users/"><span>USERS</span></a></li>
	      <li><a href="/backend/contents/"><span>CONTENT</span></a></li>
	      <li><a href="/backend/layers/" class="current"><span>LAYERS</span></a></li>
	    </ul>
	  </div>
	</div>


    {% block content %}{% endblock %}
    <br class="clear" />


</div>

</body>
</html>

templates/backend/contents.html
{% extends "backend/base.html" %}


<!-- Bloque heredado de "base.html": 
{% block content %} 
<div id="content">
	<h3>Notes (text)</h3>
	
	<form action="/backend/content/note/create/" method="POST">
		<table> 	
        	<tr><th><label>Titulo</label>:</th><td><input type="text" name="title"/></td></tr> 
	    	<tr><th><label>Texto</label>:</th><td><textarea name="text" cols="30"></textarea></td></tr> 
	    	<tr><th><label>Latitude</label>:</th><td><input type="text" name="latitude"/></td></tr> 
	    	<tr><th><label>Longitude</label>:</th><td><input type="text" name="longitude"/></td></tr> 
	    	<tr><th>Upload to Layer</th><td>
	    		<SELECT NAME="layer">                 
	    			{% for layer in results %}
	    				<OPTION VALUE="{{layer.id}}">{{layer.name}}</OPTION>
	    			{% endfor %}
	    		</SELECT> 
	    	</td></tr>
	    	
	    	<tr><th><label>Fecha expiración to (HH:MM:SS-YYYY/MM/DD TZ)</label>:</th><td><input type="text" name="avaliable_to"/></td></tr> 
	    	<tr><th><label>Fecha expiración from (HH:MM:SS-YYYY/MM/DD TZ)</label>:</th><td><input type="text" name="avaliable_from"/></td></tr> 
	    </table> 
	    <p><input type="submit" value="Upload Note" /></p>
	</form>
	
	<br>
	
	<h3>Photos </h3>
		
	<form action="/backend/content/photo/create/" method="POST" enctype="multipart/form-data"> 
        <table> 
            <tr><th><label for="id_name">Image name:</label></th><td><input id="id_name" type="text" name="name" maxlength="30" /></td></tr> 
<tr><th><label for="id_photo">Photo:</label></th><td><input type="file" name="photo" id="id_photo" /><br />Upload an image (max 500 kilobytes)</td></tr> 
            <tr><th><label for="id_desc">Description</label>:</th><td><textarea cols="30" name="description"></textarea></td></tr> 
            <tr><th><label for="id_lat">Latitude</label>:</th><td><input type="text" name="latitude" /></td></tr> 
            <tr><th><label for="id_long">Longitude</label>:</th><td><input type="text" name="longitude" /></td></tr> 
            
            <tr><th>Upload to Layer</th><td>
	    		<SELECT NAME="layer">                 
	    			{% for layer in results %}
	    				<OPTION VALUE="{{layer.id}}">{{layer.name}}</OPTION>
	    			{% endfor %}
	    		</SELECT> 
	    	</td></tr>
	    	
            <tr><th<label>Fecha expiración to (HH:MM:SS-YYYY/MM/DD TZ)</label>:</th><td><input type="text" name="avaliable_to"/></td></tr>  
            <tr><th<label>Fecha expiración from (HH:MM:SS-YYYY/MM/DD TZ)</label>:</th><td><input type="text" name="avaliable_from"/></td></tr> 
        </table>  
        <p><input type="submit" value="Upload Photo"></p> 
    </form> 
	
	<h3>Sound</h3>
	<form action="/backend/content/sound/create/" method="POST" enctype="multipart/form-data"> 
        <table> 
            <tr><th><label for="id_name">Sound file name:</label></th><td><input id="id_name" type="text" name="name" maxlength="30" /></td></tr> 
<tr><th><label for="id_sound">Sound:</label></th><td><input type="file" name="sound" id="id_sound" /><br />Upload a sound file</td></tr> 
            <tr><th><label for="id_desc">Description</label>:</th><td><textarea cols="30" name="description"></textarea></td></tr> 
            <tr><th><label for="id_lat">Latitude</label>:</th><td><input type="text" name="latitude" /></td></tr> 
            <tr><th><label for="id_long">Longitude</label>:</th><td><input type="text" name="longitude" /></td></tr> 
            
            <tr><th>Upload to Layer</th><td>
	    		<SELECT NAME="layer">                 
	    			{% for layer in results %}
	    				<OPTION VALUE="{{layer.id}}">{{layer.name}}</OPTION>
	    			{% endfor %}
	    		</SELECT> 
	    	</td></tr>
	    	
            <tr><th<label>Fecha expiración to (HH:MM:SS-YYYY/MM/DD TZ)</label>:</th><td><input type="text" name="avaliable_to"/></td></tr>  
            <tr><th<label>Fecha expiración from (HH:MM:SS-YYYY/MM/DD TZ)</label>:</th><td><input type="text" name="avaliable_from"/></td></tr>
        </table> 
        <p><input type="submit" value="Upload Sound"></p> 
    </form> 
	
	<b> {{ msg }} </b>
	
</div>

{% endblock %}

templates/backend/home.html
{% extends "backend/base.html" %}


<!-- Bloque heredado de "base.html": 
{% block content %} 

{% endblock %}

templates/backend/layers.html
{% extends "backend/base.html" %}


<!-- Bloque heredado de "base.html": 
{% block content %} 
<div id="content">
	<h3> Layers </h3>
	
	<table summary="layers"> 
			
			<thead> 
				<tr> 
					<th scope="col">Name</th> 
					<th scope="col">Description</th> 
					<th scope="col"></th> 
					<th scope="col">Icon</th> 
				</tr> 
			</thead>	
 
			<tbody> 
			
	{% for node in list %}
	  <tr>
		<td>{{node.title}}</td> 
		<td>{{node.description}}</td> 
	  </tr>	
	{% endfor %}
	
	{% for layer in results %}

	  <tr > 
	     
		 <th scope="row"><a href="/backend/layers/{{layer.id}}/">{{layer.name}}</a></th> 
		 <td>{{layer.description}}</td> 
		 <td> <form action="/backend/layers/delete/" method="POST"> 
		         <input type="submit" value="Delete"/>
		         <input type="hidden" name="id" value={{layer.id}}>
		      </form>
		 </td>
		 <td><img height="40px" src="/social/layer/{{layer.id}}/icon/"/></td>
		 
	  </tr> 
		
	{% endfor %}
	
	</tbody>		
	</table> 
	
	<br />
	<h3> Create Layer </h3>
	
	<form action="{{ url_create_layer }}" method="POST">
    	<label>Name</label>:<input type="text" name="name"/><br>
   		<label>Description</label>:<br/>
    	<textarea name="description" cols="40"></textarea><br/>
   		<label>Latitude</label>:<input type="text" name="latitude"/><br>
    	<label>Longitude</label>:<input type="text" name="longitude"/><br>
   		<input type="submit" value="Send" />
   		<input type="hidden" name="format" value="JSON">
	</form>
	
	<b> {{ msg }} </b>
</div>

{% endblock %}

templates/backend/node_list.html
{% extends "backend/base.html" %}


<!-- Bloque heredado de "base.html": 
{% block content %} 
<div id="content">
	<h3> Layer Content: {{ layer.name }} </h3>
	
	<h4>Export content layer: 
	    <a href="/social/layer/{{layer_id}}/search/?search=&latitude=0.0&longitude=0.0&radius=0&category=0&elems=100000&format=JSON">[JSON]</a>
	    <a href="/social/layer/{{layer_id}}/search/?search=&latitude=0.0&longitude=0.0&radius=0&category=0&elems=100000&format=XML">[XML]</a>
	</h4>
	
	<table summary="layers"> 
			
			<thead> 
				<tr> 
					<th scope="col">Id</th>
					<th scope="col">Type</th>
					<th scope="col">Name</th> 
					<th scope="col">Description</th> 
					<th scope="col">Image</th> 
					<th scope="col">Location</th>
					<th scope="col">Actions</th>
				</tr> 
			</thead>	
 
			<tbody> 
		
		
	{% for node in list %}
	  <tr>
	    <td>{{node.id}}</td>
	    <td>{{node.type}}</td>
		<th scope="row">{% if node.type == "photo" %} {{node.name}} {% else %} {{node.title}} {% endif %} </th> 
		<td>{{node.description}}</td> 
		<td>
		   {% if node.type == "photo" %}
		   	<img width="200" src="http://0.0.0.0:9001/social/layer/{{layer_id}}/node/{{node.id}}/image/">
		   {% endif %}
		</td>
		<td>
			<a href="http://maps.google.es/maps?f=q&source=s_q&hl=es&geocode=&q={{node.position.y}},+{{node.position.x}}&sspn=0.003443,0.006968&ie=UTF8&t=h&z=17">View Map</a>
		</td>
		
		<td><a href="/backend/layers/{{layer_id}}/node/{{node.id}}/delete/">Delete</a>
	  </tr>	
	  
	{% endfor %}
	
	</tbody>		
	</table> 
	
	<br />
	<b> {{ msg }} </b>
</div>

{% endblock %}