urls.py
from django.conf.urls import patterns, include, url
import os
from os.path import join

from settings import MEDIA_ROOT, APPS_DIR, BASEDIR, INFOMEDIA_ROOT

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lgs.views.home', name='home'),
    # url(r'^lgs/', include('lgs.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^version/', 'social.rest.views.version',),
    url(r'^social/',include('social.rest.urls'),),
    url(r'^backend/',include('backend.urls'),),
    url(r'^site_media/images/photos','social.rest.views.forbbiden_photo',),
    url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':MEDIA_ROOT}),
    url(r'^agregador/', include('agregador.urls'),),
    url(r'^infomedia/(?P<path>.*)$','django.views.static.serve',{'document_root':INFOMEDIA_ROOT}),
)


def look_up_apps():
    apps_dir = join(BASEDIR,APPS_DIR)
    print apps_dir
    dirs = os.listdir(apps_dir)
    pat = urlpatterns
    for dir in dirs:
        if os.path.isdir(join(apps_dir,dir)) and dir[0] not in ('.','_'):
            urls=r'^%s/' % dir
            urls_file='%s.%s.urls' % (APPS_DIR,dir)
            pat= pat + patterns('',(urls,include(urls_file)))
    return pat




try:
    urlpatterns= look_up_apps()
except:
    pass

social/core/models.py
#
#  Copyright (C) 2009 GSyC/LibreSoft
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU Affero General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU Affero General Public License for more details.
#
#	You should have received a copy of the GNU Affero General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
#	Author : Jose Antonio Santos Cadenas <jcaden __at__ gsyc __dot__ es>
#

from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.core.files.storage import FileSystemStorage

from social.privacy2.utils import get_object_status, get_fields
import social.privacy2.utils as privacy

from datetime import datetime

from social.privacy.exceptions import PermissionError
from utils import get_fields_for_groups, get_group_for_field


	
class Tag(models.Model):
	"""
	Model for tag social objects
	"""
	tag = models.CharField(max_length=200, unique=True)
	
	objects = models.GeoManager()
	
	def get_search_fields(self):
		return ["tag"]
	
	def __unicode__(self):
		return u"%s" % self.tag
	
class Comment(models.Model):
	"""
	Allows comments on an object
	"""
	comment = models.TextField()
	
	date = models.DateTimeField(default=datetime.now(), editable=False)
	author = models.ForeignKey("Person", related_name="my_comments")
	node = models.ForeignKey("Social_node", related_name="comments")

	def get_dictionary(self):
		"""
		Returns a dictionary with the comment data
		"""
		dict = {"id"			  : self.id,
				"author" : { "id"	   : self.author.id,
							 "username" : self.author.username,
						   },
				"comment"		 : self.comment,
				"date"			: self.date
			   }
		return dict

class Social_node(models.Model):
	"""
	General social object, can be related with any other 
	social object
	"""
	position = models.PointField(srid=4326)
	altitude = models.FloatField(help_text="In meters over the sea level", default=0.0)
	radius = models.FloatField(default=0.0)
	pos_time = models.DateTimeField(default=datetime.now)
	since = models.DateTimeField(default=datetime.now)
	tags = models.ManyToManyField(Tag)
	type = models.CharField(max_length=50, editable=False)
	icon = models.CharField(max_length=200, null=True)
	avaliable_to = models.DateTimeField(null = True)
	avaliable_from = models.DateTimeField(null = True)
	# currently not used, maybe future features
	visible = models.BooleanField(default = True)
	
	info_url = models.CharField(max_length=200, null = True)
	
	objects = models.GeoManager()
	
	def save(self, force_insert=False, force_update=False):
		if not self.pk: #The first time
			m = ""
			for t in self._meta.get_parent_list():
				if t._meta.object_name.lower() != "social_node":
					if m == "":
						m = "%s" % (t._meta.object_name.lower())
					else:
						m = "%s.%s" % (m, t._meta.object_name.lower())
			if m == "":
				self.type = "%s" % self._meta.object_name.lower()
			else:	
				self.type = "%s.%s" % (m, self._meta.object_name.lower())
				
		"""
			There is a problem with the hierarchy of LGS Person (user.person). But, we dont have
			a user model, so this type could make problems. So, we have to forget the user class
		"""
		if self.type.find("user.") == 0:
			self.type = self.type.replace("user.", "") 
		return super(Social_node, self).save(force_insert, force_update)
	
	def get_type(self):
		try:
			if self.person.id == self.id:
				return "person"
		except:
			pass
		try:  
			if self.group.id == self.id:
				return "group"
		except:
			pass
		try:
			if self.note.id == self.id:
				return "note"
		except:
			pass
		try:
			if self.photo != None:
				return "photo"
		except:
			pass
		return "social_node"
	
	def get_node(self):
		try:
			node = eval("self.%s" % self.type)
			if isinstance(node, Social_node):
				try:
					node.distance = self.distance
				except:
					pass
				return node
		except:
			pass
		return self
	
	def get_owner(self):
		node = self.get_node()
		if node != self:
			return node.get_owner()
		else:
			return self
	
	def get_dictionary(self, viewer=None):
		"""
		Returns a dictionary with the node data
		"""
		dict = {"id"		: self.id,
				"position"  : {"latitude"  : self.position.get_y(),
							   "longitude" : self.position.get_x(),
							   "radius"	: self.radius,
							   "since"	 : self.pos_time,
							   "altitude"  : self.altitude,
							   },
				"since"	 : self.since,
				"type"	  : self.type,
				"tags"	  : [t.tag for t in self.tags.all()],
				"icon"	   : self.icon,
				"info_url" : self.info_url}
		try:
			dict["position"]["distance"]= round (self.distance.m,2)
		except:
			pass
		if viewer != None and viewer.id!=self.id:
			obj = self.get_node()
			groups= get_fields(obj, viewer)
			if groups==None:
				raise PermissionError("Element not allowed")
			fields= get_fields_for_groups(self, groups)
			if "id" not in fields:
				dict.pop("id")
			if "position" not in fields:
				pos=dict["position"]
				pos.pop("latitude")
				pos.pop("longitude")
				pos.pop("altitude")
				try:
					pos.pop("distance")
				except:
					pass
			if "radius" not in fields:
				dict["position"].pop("radius")
			if "pos_time" not in fields:
				dict["position"].pop("since")
			if dict["position"]=={}:
				dict.pop("position")
			if "since" not in fields:
				dict.pop("since")
		return dict

	def get_privacy(self):
		"""
		Returns a dictionary with the allowed and forbidden roles for each field
		"""
		object = self.get_node()
		sec = get_object_status(object)
		dict = self.get_dictionary()
		dict["allowed_all"]= sec["full"]
		dict["forbidden_all"]= sec["forbidden"]
		g=get_group_for_field(self, "id")
		
		dict["id"]={"value": dict["id"],
					"allowed": sec["fields_allowed"][g],
					"forbidden": sec["fields_forbidden"][g]}
		
		#self._get_location_privacy(dict)
		g=get_group_for_field(self, "position")
		dict["position"]["latitude"]={"value": dict["position"]["latitude"],
									  "allowed": sec["fields_allowed"][g],
									  "forbidden": sec["fields_forbidden"][g]}
		dict["position"]["longitude"]={"value": dict["position"]["longitude"],
									   "allowed": sec["fields_allowed"][g],
									   "forbidden": sec["fields_forbidden"][g]}
		dict["position"]["altitude"]={"value": dict["position"]["altitude"],
									   "allowed": sec["fields_allowed"][g],
									   "forbidden": sec["fields_forbidden"][g]}
		g=get_group_for_field(self, "radius")
		dict["position"]["radius"]={"value": dict["position"]["radius"],
									"allowed": sec["fields_allowed"][g],
									"forbidden": sec["fields_forbidden"][g]}
		g=get_group_for_field(self, "pos_time")
		dict["position"]["since"]={"value": dict["position"]["since"],
								   "allowed": sec["fields_allowed"][g],
								   "forbidden": sec["fields_forbidden"][g]}
	 
		g=get_group_for_field(self, "since")
		dict["since"]={"value": dict["since"],
					   "allowed": sec["fields_allowed"][g],
					   "forbidden": sec["fields_forbidden"][g]}
		return dict
	
	get_search_fields= []
	
	def set_perm(self, perm):
		return privacy.set_perm(self, perm)
	
	def set_perm_field(self, field, perm):
		return privacy.set_perm_field(self, field, perm)

	
	def delete(self, viewer):
		try:
			person = Person.objects.get(pk = viewer)
		except Exception, err:
			raise err
	
		super(Social_node, self).delete()


	@models.permalink
	def get_absolute_url(self):
		return ('node_data', [str(self.id)])
	
	def __unicode__(self):
		return u"social node %s" % self.pk

	
try: 
	from south.modelsinspector import add_introspection_rules
except ImportError: #ok, you dont have south in your system or you dont want to use it
	pass


class PersonManager(models.GeoManager):
	
	def allowed(self, viewer_id):
		return self.extra(where=[" social_node_ptr_id in (select * from get_persons_visibles(%s))" % viewer_id ])

class Person(Social_node, User):
	"""
	Represents a person in social networks issues
	"""
	status = models.CharField(max_length=500, default="")
	status_time = models.DateTimeField(default=datetime.now)
	birthday = models.DateField(null=True)
	post_code = models.CharField(max_length=15, null=True)
	country = models.CharField(max_length=2, null=True)
	avatar = models.ForeignKey("Photo", related_name="avatar_of", null=True)
	
	objects = PersonManager()

	def is_friend(self, friend):
		if Friendship.objects.are_friends(self, friend):
			return True
		else:
			return False
		
	def get_owner(self):
		return self

	def get_dictionary(self, viewer=None):
		"""
			Returns the person data as a dictionary
		"""
		dict = Social_node.get_dictionary(self, viewer)

		dict.setdefault("position", {})
		if self.country:
			dict['position']['country'] = self.country
		if self.post_code:
			dict['position']['post_code'] = self.post_code 
		dict['name']	 = self.get_full_name()
		dict['first_name'] = self.first_name
		dict['last_name']  = self.last_name
		dict['username'] = self.username
		dict['status']   = {"message":self.status,
							"since"  :self.status_time,
						   }
		dict['email']	= self.email
		if self.avatar:
			dict['avatar'] = {"id"  : self.avatar.id,
							  "url" : self.avatar.get_absolute_image_url()}
		if self.birthday:
			dict['birthday'] = self.birthday
			
		if viewer !=None and viewer!=self:
			groups = get_fields(self, viewer)
			if groups==None:
				raise PermissionError("Element not allowed")
			fields= get_fields_for_groups(self, groups)
			if "name" not in fields:
				dict.pop("name")
			if "first_name" not in fields:
				dict.pop("first_name")
			if "last_name" not in fields:
				dict.pop("last_name")
			if "username" not in fields:
				dict.pop("username")
			if "status" not in fields:
				dict["status"].pop("message")

templates/social_test.html
<script type="text/javascript">
    function redirect_user(user){
        location.href='/social/user/'+user+'/data/'
    }
    
    function redirect_group(group){
      location.href='/social/group/'+group+'/data/'
   }
</script>



{% url user_create as url_user_create %}
<form action="{{ url_user_create }}" method="POST">
    Crear usuario:<br>
    <label>Username</label>*:<input type="text" name="username"/><br>
    <label>Password</label>*:<input type="password" name="password"/><br>
    
    <input type="submit" value="Enviar" />
</form>


{% url user_login as url_user_login %}
<form action="{{ url_user_login }}" method="POST">
   Login:<br>
   <label>Nombre</label>*:<input type="text" name="username"/><br>
    <label>Password</label>*:<input type="password" name="password"/><br>
   <input type="submit" value="Enviar" />
</form>

{% url user_set_status as url_user_set_status %}
<form action="{{ url_user_set_status }}" method="POST">
   Estado:<br>
   <label>Estado</label>:<input type="text" name="status"/><br>
   <input type="submit" value="Enviar" />
</form>

{% url user_pos as url_user_pos %}
<form action="{{ url_user_pos }}" method="POST">
    Establecer posición:<br>
    <label>Longitude</label>:<input type="text" name="longitude"/><br>
    <label>Latitude</label>:<input type="text" name="latitude"/><br>
    <input type="submit" value="Enviar" />
</form>

<form name="userData" action='javascript:redirect_user(document.userData.userid.value);'>
   Datos usuario:<br>
   <label>Id</label>:<input type="text" name="userid"/><br>
   <input type="submit" value="Enviar" />
</form>

{% url user_delete as url_user_delete %}
<form action="{{ url_user_delete }}" method="POST">
   Borrar usuario:<br>
   <label>Id</label>:<input type="text" name="userid"/><br>
   <input type="submit" value="Enviar" />
</form>

{% url user_relation as url_user_relation %}
<form action="{{ url_user_relation }}" method="POST">
   Amistad:<br>
   <label>Id1</label>:<input type="text" name="userid1"/><br>
    <label>Id2</label>:<input type="text" name="userid2"/><br>
   <input type="submit" value="Enviar" />
</form>

{% url user_relation_delete as url_user_relation_delete %}
<form action="{{ url_user_relation_delete }}" method="POST">
   Borrar amistad:<br>
   <label>Id1</label>:<input type="text" name="userid1"/><br>
   <label>Id2</label>:<input type="text" name="userid2"/><br>
   <input type="submit" value="Enviar" />
</form>

{% url group_create as url_group_create %}
<form action="{{ url_group_create }}" method="POST">
   Crear grupo:<br>
   <label>Nombre grupo</label>:<input type="text" name="groupname"/><br>
   <input type="submit" value="Enviar" />
</form>

<form name="groupData" action='javascript:redirect_group(document.groupData.groupid.value);'>
   Datos grupo:<br>
   <label>Id</label>:<input type="text" name="groupid"/><br>
   <input type="submit" value="Enviar" />
</form>

{% url group_delete as url_group_delete %}
<form action="{{ url_group_delete }}" method="POST">
   Borrar grupo:<br>
   <label>Id grupo</label>:<input type="text" name="groupid"/><br>
   <input type="submit" value="Enviar" />
</form>

{% url group_join as url_group_join %}
<form action="{{ url_group_join }}" method="POST">
   Unirse a un grupo:<br>
   <label>Id grupo</label>:<input type="text" name="groupid"/><br>
   <label>Id nuevo miembro</label>:<input type="text" name="userid"/><br>
   <input type="submit" value="Enviar" />
</form>

{% url group_unjoin as url_group_unjoin %}
<form action="{{ url_group_unjoin }}" method="POST">
   Borrarse de un grupo:<br>
   <label>Id grupo</label>:<input type="text" name="groupid"/><br>
   <label>Id miembro</label>:<input type="text" name="userid"/><br>
   <input type="submit" value="Enviar" />
</form>

{% url note_upload as url_create_note %}
<form action="layer/19/note/upload/" method="POST">
   Crear una nota:<br>
    <label>Titulo</label>:<input type="text" name="title"/><br>
   <label>Texto</label>:<br/>
    <textarea name="text"></textarea><br/>
    <label>Fecha expiración to (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_to"/><br>
    <label>Fecha expiración from (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_from"/><br>
   <label>Latitude</label>:<input type="text" name="latitude"/><br>
    <label>Longitude</label>:<input type="text" name="longitude"/><br>
   <input type="submit" value="Enviar" />
</form>


{% url photo_upload as url_photo_upload%}
    <form action="http://192.168.2.7:10502/compareImages/social/compare/" method="POST" enctype="multipart/form-data">
      Comparar una foto:
        <table>
            {{ compare_form.as_table }}
            <tr><th><label for="id_radius">Radius</label>:</th><td><input type="text" name="radius" /></td></tr>
            <tr><th><label for="id_lat">Latitude</label>:</th><td><input type="text" name="latitude" /></td></tr>
            <tr><th><label for="id_long">Longitude</label>:</th><td><input type="text" name="longitude" /></td></tr>
        </table>
        <label>Fecha expiración to (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_to"/><br>
        <label>Fecha expiración from (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_from"/><br>
        <p><input type="submit" value="Enviar"></p>
    </form>

{% url photo_upload as url_photo_upload%}
    <form action="layer/19/photo/upload/" method="POST" enctype="multipart/form-data">
      Enviar una foto:
        <table>
            {{ photo_form.as_table }}
            <tr><th><label for="id_desc">Description</label>:</th><td><textarea name="description"></textarea></td></tr>
            <tr><th><label for="id_lat">Latitude</label>:</th><td><input type="text" name="latitude" /></td></tr>
            <tr><th><label for="id_long">Longitude</label>:</th><td><input type="text" name="longitude" /></td></tr>
        </table>
        <label>Fecha expiración to (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_to"/><br>
        <label>Fecha expiración from (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_from"/><br>
        <p><input type="submit" value="Enviar"></p>
    </form>

{% url sound_upload as url_sound_upload%}
    <form action="layer/19/sound/upload/" method="POST" enctype="multipart/form-data">
      Enviar un sonido:
        <table>
            {{ sound_form.as_table }}
            <tr><th><label for="id_desc">Description</label>:</th><td><textarea name="description"></textarea></td></tr>
            <tr><th><label for="id_lat">Latitude</label>:</th><td><input type="text" name="latitude" /></td></tr>
            <tr><th><label for="id_long">Longitude</label>:</th><td><input type="text" name="longitude" /></td></tr>
        </table>
        <label>Fecha expiración to (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_to"/><br>
        <label>Fecha expiración from (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_from"/><br>
        <p><input type="submit" value="Enviar"></p>
    </form>


{% url video_upload as url_video_upload%}
    <form action="layer/19/video/upload/" method="POST" enctype="multipart/form-data">
      Enviar un video:
        <table>
            {{ video_form.as_table }}
            <tr><th><label for="id_desc">Description</label>:</th><td><textarea name="description"></textarea></td></tr>
            <tr><th><label for="id_lat">Latitude</label>:</th><td><input type="text" name="latitude" /></td></tr>
            <tr><th><label for="id_long">Longitude</label>:</th><td><input type="text" name="longitude" /></td></tr>
        </table>
        <label>Fecha expiración to (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_to"/><br>
        <label>Fecha expiración from (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_from"/><br>
        <p><input type="submit" value="Enviar"></p>
    </form>


{% url node_set_dates as url_node_set_dates%}
    <form action="layer/19/node/119/update_avaliable_dates/" method="POST" enctype="multipart/form-data">
      Cambiar fechas de un nodo:
        <label>Fecha expiración to (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_to"/><br>
        <label>Fecha expiración from (HH:MM:SS-YYYY/MM/DD TZ)</label>:<input type="text" name="avaliable_from"/><br>
        <p><input type="submit" value="Enviar"></p>
    </form>

{% url create_layer as url_create_layer %}
<form action="{{ url_create_layer }}" method="POST">
   Create Layer:<br>
    <label>Nam</label>:<input type="text" name="name"/><br>
   <label>Description</label>:<br/>
    <textarea name="description"></textarea><br/>
   <label>Latitude</label>:<input type="text" name="latitude"/><br>
    <label>Longitude</label>:<input type="text" name="longitude"/><br>
   <input type="submit" value="Send" />
</form>


{% url icon_change_layer as url_icon_change_layer %}
<form action="layer/84/change_icon/" method="POST" enctype="multipart/form-data">
		Change icon:
   		<table>
            {{ icon_form.as_table }}
            
        </table>
        
        <p><input type="submit" value="Enviar"></p>
</form>



<hr/><!-- ------------------------------------------------------------------------- -->
{% url change_privacy as url_change_privacy %}
<form action="/social/node/65/privacy/change/" method="POST">
   Change node permissions:<br>
   <label>Perm</label>:<select type="text" name="perm">
               <option value=""></option>
               <option value="Private">Private</option>
               <option value="Friends">Friends</option>
               <option value="Friends_of_friends">Friends of friends</option>
	       <option value="Public">Public</option>
               <option value="fake">fake</option>
               </select>
               <br>          
   <input type="submit" value="Enviar" />
</form>

{% url node_change_privacy as url_node_change_privacy %}
<form action="/social/node/65/privacy/change/" method="POST">
   Change node permissions:<br>
   <label>Perm</label>:<select type="text" name="perm">
               <option value=""></option>
               <option value="Private">Private</option>
               <option value="Friends">Friends</option>
               <option value="Friends_of_friends">Friends of friends</option>
	       <option value="Public">Public</option>
               <option value="fake">fake</option>
               </select>
               <br>       
    
   <label>Field</label>:<select type="text" name="field">
               <option value="position">position</option>
               
               </select>
               <br>
    <label>Id:</label><input type="text" name="node_id" id="node_id"/><br>    
   <input type="submit" value="Enviar" />
</form>

<hr/><!-- ------------------------------------------------------------------------- -->
<h2>Semantic Module</h2>

{% url similarSemantic as similar_semantic %}
<form action="{{ similar_semantic }}" method="GET">
    How similarity are these two words:<br>
    <label>Word1</label>:<input type="text" name="word1"/><br>
    <label>Word2</label>:<input type="text" name="word2"/><br>
    <input type="submit" value="Send" />
</form>

{% url socialSemanticSearch as semantic_search %}
<form action="{{ semantic_search }}" method="GET">
    Semantic search in different social nodes:<br>
    <label>Search</label>:<input type="text" name="word"/><br>
    <label>Sense</label>:<input type="text" name="sense" value="0"/><br>
	<INPUT TYPE=CHECKBOX NAME="checkPhotos" CHECKED value="True" >Photos<BR>
	<INPUT TYPE=CHECKBOX NAME="checkNotes"  value="True" >Notes<BR>
    <input type="submit" value="Send" />
</form>

{% url compareNodesSemantic as compare_nodes %}
<form action="{{ compare_nodes }}" method="GET">
    Compare social nodes:<br>
    <label>Distance Min</label>:<input type="text" name="min"/><br>
    <input type="submit" value="Send" />
</form>


#}