apps/gymkhana/urls.py
#
#  Copyright (C) 2009 GSyC/LibreSoft
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>._
# 
#    Author : Jorge Fernandez Gonzalez <jorge.fernandez.gonzalez __at__ gmail.com>
#

from django.conf.urls.defaults import *
# Django settings for server project.
import sys
from os.path import abspath, dirname, join
#import deseb
from os import path
from django.views.generic.simple import direct_to_template

BASEDIR = path.dirname(path.abspath(__file__))
MODIFIED = path.join(BASEDIR,'templates')

from apps.gymkhana.rest import views

urlpatterns = patterns('',
    (r'templates/(?P<path>.*)$','django.views.static.serve',{'document_root': 'apps/gymkhana/templates'}),
    (r'img/(?P<path>.*)$','django.views.static.serve',{'document_root': 'apps/gymkhana/img'}),

    (r'^$', 'apps.gymkhana.rest.views.event_list'),
    (r'^overall_standings/show/$', 'apps.gymkhana.rest.views.overall_standings_show'),
    (r'^my_standings/show/$', 'apps.gymkhana.rest.views.my_standings_show'),
    (r'^event/list/$', 'apps.gymkhana.rest.views.event_list'),
    (r'^event/create/$', 'apps.gymkhana.rest.views.event_create'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/show/$', 'apps.gymkhana.rest.views.event_show'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/set_status/$', 'apps.gymkhana.rest.views.event_set_status'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/delete/$', 'apps.gymkhana.rest.views.event_delete'),

    (r'^user/create/$', 'apps.gymkhana.rest.views.user_create'),
    (r'^user/logout/$', 'apps.gymkhana.rest.views.user_logout'),
    (r'^user/login/$', 'apps.gymkhana.rest.views.user_login'),
    (r'^user/list/$', 'apps.gymkhana.rest.views.user_list'),
    (r'^user/(?P<user_id>[1-9][0-9]*)/show/$', 'apps.gymkhana.rest.views.user_show'),
    (r'^user/(?P<user_id>[1-9][0-9]*)/edit/$', 'apps.gymkhana.rest.views.user_edit'),
    (r'^user/(?P<user_id>[1-9][0-9]*)/delete/$', 'apps.gymkhana.rest.views.user_delete'),

    (r'^event/(?P<event_id>[1-9][0-9]*)/message/create/$', 'apps.gymkhana.rest.views.message_create'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/message/list/$', 'apps.gymkhana.rest.views.message_list'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/message/(?P<message_id>[1-9][0-9]*)/reply/$', 'apps.gymkhana.rest.views.message_reply'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/message/(?P<message_id>[1-9][0-9]*)/delete/$', 'apps.gymkhana.rest.views.message_delete'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/message/list/delete/$', 'apps.gymkhana.rest.views.message_list_delete'),

    (r'^event/(?P<event_id>[1-9][0-9]*)/team/team_member/create/$', 'apps.gymkhana.rest.views.team_member_create'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/team_member/(?P<team_member_id>[1-9][0-9]*)/delete/$', 'apps.gymkhana.rest.views.team_member_delete'),

    (r'^event/(?P<event_id>[1-9][0-9]*)/response/(?P<response_id>[1-9][0-9]*)/edit/$', 'apps.gymkhana.rest.views.response_edit'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/response/(?P<response_id>[1-9][0-9]*)/delete/$', 'apps.gymkhana.rest.views.response_delete'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/response/list/$', 'apps.gymkhana.rest.views.response_list'),

    (r'^event/(?P<event_id>[1-9][0-9]*)/team/list/$', 'apps.gymkhana.rest.views.team_list'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/show/$', 'apps.gymkhana.rest.views.team_show'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/create/$', 'apps.gymkhana.rest.views.team_create'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/edit/$', 'apps.gymkhana.rest.views.team_edit'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/monitoring/$', 'apps.gymkhana.rest.views.monitoring'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/information_gymkhana/$', 'apps.gymkhana.rest.views.team_get_information_gymkhana'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/information_gymkhana/$', 'apps.gymkhana.rest.views.team_get_information_gymkhana'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/delete/$', 'apps.gymkhana.rest.views.team_delete'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/message/list_inbox/$', 'apps.gymkhana.rest.views.team_show_inbox_messages'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/message/list_sent/$', 'apps.gymkhana.rest.views.team_show_sent_messages'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/message/num_inbox/$', 'apps.gymkhana.rest.views.number_team_inbox_messages'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/message/num_sent/$', 'apps.gymkhana.rest.views.number_team_sent_messages'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/skipped_challenge/list/$', 'apps.gymkhana.rest.views.skipped_challenge_list'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/join/$', 'apps.gymkhana.rest.views.team_join'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/subscribe/$', 'apps.gymkhana.rest.views.team_subscribe'),

    (r'^event/(?P<event_id>[1-9][0-9]*)/team_member/has_team/$', 'apps.gymkhana.rest.views.team_member_has_team'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team_member/previous_teams/$', 'apps.gymkhana.rest.views.team_member_previous_teams'),

    (r'^event/(?P<event_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/delete/$', 'apps.gymkhana.rest.views.challenge_delete'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/challenge/create/$', 'apps.gymkhana.rest.views.challenge_create'),

    (r'^event/(?P<event_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/show/$', 'apps.gymkhana.rest.views.challenge_show'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/respond/$', 'apps.gymkhana.rest.views.challenge_respond'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/skip/$', 'apps.gymkhana.rest.views.challenge_skip'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/clue/buy/$', 'apps.gymkhana.rest.views.clue_buy'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/clue/show/$', 'apps.gymkhana.rest.views.clue_show'),
    (r'^mobile/menu/$', 'apps.gymkhana.rest.views.mobile_menu'),
    (r'^mobile/login/$', 'apps.gymkhana.rest.views.mobile_login'),
    (r'^mobile/gymkhanas/$', 'apps.gymkhana.rest.views.mobile_gymkhanas'),
    (r'^new_user/$', 'apps.gymkhana.rest.views.new_user'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/list_teams/$', 'apps.gymkhana.rest.views.list_teams'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/start/$', 'apps.gymkhana.rest.views.start'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/event_show/$', 'apps.gymkhana.rest.views.mobile_event_show'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/end/$', 'apps.gymkhana.rest.views.end'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/show_list_clues/$', 'apps.gymkhana.rest.views.show_list_clues'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/get_clue/$', 'apps.gymkhana.rest.views.get_clue'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/list_clues/$', 'apps.gymkhana.rest.views.list_clues'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/finish/$', direct_to_template, {'template': 'dialogs/finish.html'}),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/ask_skip/$', 'apps.gymkhana.rest.views.ask_skip'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/skip_list/$', 'apps.gymkhana.rest.views.skip_list'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/challenge/(?P<challenge_id>[1-9][0-9]*)/skip/$', 'apps.gymkhana.rest.views.skip_challenge'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/process_message/$', 'apps.gymkhana.rest.views.process_message'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/show_messages/$', 'apps.gymkhana.rest.views.show_messages'),
    (r'^event/(?P<event_id>[1-9][0-9]*)/team/(?P<team_id>[1-9][0-9]*)/parameters/$', 'apps.gymkhana.rest.views.parameters'),
    (r'^rankings/$', 'apps.gymkhana.rest.views.show_ranking'),
    (r'^logout/$', 'apps.gymkhana.rest.views.mobile_logout'),
)

urls.py
from django.conf.urls import patterns, include, url
import os
from os.path import join

from settings import MEDIA_ROOT, APPS_DIR, BASEDIR, INFOMEDIA_ROOT

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lgs.views.home', name='home'),
    # url(r'^lgs/', include('lgs.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^version/', 'social.rest.views.version',),
    url(r'^social/',include('social.rest.urls'),),
    url(r'^backend/',include('backend.urls'),),
    url(r'^site_media/images/photos','social.rest.views.forbbiden_photo',),
    url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':MEDIA_ROOT}),
    url(r'^agregador/', include('agregador.urls'),),
    url(r'^infomedia/(?P<path>.*)$','django.views.static.serve',{'document_root':INFOMEDIA_ROOT}),
)


def look_up_apps():
    apps_dir = join(BASEDIR,APPS_DIR)
    print apps_dir
    dirs = os.listdir(apps_dir)
    pat = urlpatterns
    for dir in dirs:
        if os.path.isdir(join(apps_dir,dir)) and dir[0] not in ('.','_'):
            urls=r'^%s/' % dir
            urls_file='%s.%s.urls' % (APPS_DIR,dir)
            pat= pat + patterns('',(urls,include(urls_file)))
    return pat




try:
    urlpatterns= look_up_apps()
except:
    pass

apps/gymkhana/models.py
# -*- coding: iso-8859-15 -*- 

from django.db import models

from datetime import datetime

from django.contrib.gis.db import models

from social.core.models import *

from django.core.files.storage import FileSystemStorage

from social.core.models import Social_node

#
#  Copyright (C) 2009 GSyC/LibreSoft
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
#    Author : Jorge Fernandez Gonzalez
#

class Manager(models.Model):
    user = models.ForeignKey(Person,null=False)
    events = models.ManyToManyField("Event",null=True)

class TeamMember(models.Model):
    user = models.ForeignKey(Person,null=False)
    team = models.ForeignKey("Team",null=False)
    event = models.ForeignKey("Event",null=False)

class Team(models.Model):
    group = models.ForeignKey(Group,null=False) # groupname unique (social.core.models)
    event = models.ManyToManyField("Event",null=False)
    responses = models.ManyToManyField("Response",null=True)

class Finished(models.Model):
    team = models.ForeignKey("Team",null=False)
    event = models.ForeignKey("Event",null=False)
    is_finished = models.BooleanField(null=False) # Indica si el equipo ha finalizado esta gymkhana

class AcquiredClue(models.Model):
    team = models.ForeignKey("Team",null=False)
    clue = models.ForeignKey("Clue",null=False)

class FirstChallenge(models.Model):
    event = models.ForeignKey("Event",null=False)
    team = models.ForeignKey("Team",null=False)
    first_challenge = models.ForeignKey("Challenge",null=True)

class Response(Social_node): # Almacena las respuestas que cada equipo dio a cada prueba
    challenge = models.ForeignKey("Challenge",null=False)
    response_text = models.CharField(max_length=255) #null=False
    is_correct = models.BooleanField(default=False)

    #position = models.PointField(srid=4326)
    #altitude = models.FloatField(help_text="In meters over the sea level", default=0.0)
    date = models.DateTimeField(default=datetime.now)

    photo = models.ImageField(upload_to="img", storage=FileSystemStorage())

    distance_difference = models.FloatField(default=-1)

class Clue(models.Model):
    challenge = models.ForeignKey("Challenge",null=False)
    number = models.IntegerField(null=False)
    help = models.CharField(max_length=255,null=False)
    cost = models.IntegerField(default=0,null=False)

class Challenge(models.Model):
    challenge = models.TextField(null=False)
    picture = models.ImageField(upload_to="img", storage=FileSystemStorage(),null=True)
    number = models.IntegerField(null=False)
    event = models.ForeignKey("Event",null=False)
    next_challenge_id = models.IntegerField(null=False)
    is_stop = models.BooleanField(default=False,null=False) # Indica si se necesita una respuesta correcta para poder continuar
    can_skip = models.BooleanField(default=False)
    max_score = models.IntegerField(default=100,null=False)
    challenge_type = models.IntegerField(default=1,null=False) # 1 -> Textual; 2 -> Photo; 3 -> Geolocation; ...
    augmented_reality = models.NullBooleanField(default=False,null=True) # Para las pruebas textuales, si hace uso del modulo de realidad aumentada
    target_place = models.PointField(srid=4326, null=True) # Si tipo = 3; punto geografico al que hay que llegar
    distance_to_target_place = models.FloatField(default=0.0,null=True)
    mark_place = models.NullBooleanField(default=False,null=True)
    objectives = models.ManyToManyField("LearningObjective", blank=True, null=True)

class Solution(models.Model):
    challenge = models.ForeignKey("Challenge",null=False)
    possible_solution = models.CharField(max_length=255,null=False)

class SkippedChallenge(models.Model):
    challenge = models.ForeignKey("Challenge",null=False)
    team = models.ForeignKey("Team",null=False)

class Scoreboard(models.Model):
    event = models.ForeignKey("Event",null=False)
    team = models.ForeignKey("Team",null=False)
    score = models.IntegerField(default=0,null=False)
    num_correct_responses = models.IntegerField(default=0,null=False)
    num_incorrect_responses = models.IntegerField(default=0,null=False)

class Event(models.Model):
    title = models.CharField(max_length=255,null=False)
    celebration = models.DateField(default=datetime.now(),null=False)
    place = models.CharField(max_length=255,null=False)
    welcome_text = models.TextField(null=False)
    goodbye_text = models.TextField(null=False)
    is_closed = models.BooleanField(default=True,null=False)
    language = models.CharField(max_length=255,null=True)
    configurate_teams = models.BooleanField(default=False,null=False) # True => manager will configure teams.
    image = models.ImageField(upload_to="img", storage=FileSystemStorage(), null=True)
    difficulty = models.IntegerField(default=3)
    score = models.IntegerField(default=0)
    objectives = models.ManyToManyField("LearningObjective", blank=True, null=True, related_name="learning_objectives")

class LearningObjective(models.Model):
    objective = models.CharField(max_length=255,null=False)

class Message(Social_node):
    event = models.ForeignKey("Event",null=False)
    from_manager = models.ForeignKey("Manager",blank=True,null=True,related_name="sender_manager")
    from_team = models.ForeignKey("Team",blank=True,null=True,related_name="sender_team")
    to_manager = models.ForeignKey("Manager",blank=True,null=True,related_name="receiver_manager")
    to_team = models.ManyToManyField("Team",blank=True,null=True,related_name="receiver_team")
    text = models.TextField(null=False)

    #position = models.PointField(srid=4326, null=True)
    #altitude = models.FloatField(help_text="In meters over the sea level", default=0.0, null=True)
    date = models.DateTimeField(default=datetime.now)

class Parameters(models.Model):
    event_id = models.IntegerField(null=False)
    team_id = models.IntegerField(null=False)
    time = models.DateTimeField(null=False)
    length = models.IntegerField(null=False)

apps/gymkhana/templates/challenge.html
{% extends "gymkhana.html" %}

{% block content %}
<h1>{{ challenge }}</h1>
<h2>{{ is_photo }}</h2>
<h2>{{ can_skip }}</h2>
<h2>{{ number }}</h2>
{% endblock %}

{% block contentM %}
<h1>{{ challenge }}</h1>
<h2>{{ is_photo }}</h2>
<h2>{{ can_skip }}</h2>
<h2>{{ number }}</h2>
{% endblock %}


apps/gymkhana/templates/error.html
{% extends "gymkhana.html" %}

{% block content %}
<h1>ERROR - {{ code }}<h1>
<p>{{ description }}</p>
{% endblock %}

{% block contentM %}
<h1>ERROR - {{ code }}<h1>
<p>{{ description }}</p>
{% endblock %}

apps/gymkhana/templates/list_response.html
{% extends "gymkhana.html" %}

{% block content %}

{% if teams %}
<div>
	<fieldset>
		<legend>Listing Challenges-Responses</legend>

        {% for team in teams %}
	{% for response in team.responses.all %}
		<p><b>Team: <a href="/gymkhana/event/{{ event.id }}/team/{{ team.id }}/show/" data-ajax="false">{{ team.group.name }} (identifier: {{ team.id }})</a></b></p>
		<p><b>- Challenge {{ response.proof.number }}</b> (identifier: {{ response.proof.id }})</p>
		<p><b>- Challenge:</b> {{ response.proof.challenge }}</p>
		<p><b>- Possible Solutions:</b></p>
		<ul>
			{% for solution in response.proof.solution_set.all %}
			<li>{{ solution.possible_solution }}</li>
			{% endfor %}
		</ul>

		<p><b>- Response must be Correct to Continue:</b> {{ response.proof.is_stop }}</p>
		<p><b>- Response: {{ response.response }}</b></p>
		<p><b>- Is Correct: {{ response.is_correct }}</b></p>
		<div>
			<form action="/gymkhana/event/{{ event.id }}/response/{{ response.id }}/edit/" method="get" data-ajax="false">
				<input type="hidden" name="team_id" value="{{ team.id }}">
				<input type="submit" name="change_status" value="Change to Correct/Incorrect"></input>
			</form>
			<form action="/gymkhana/event/{{ event.id }}/response/{{ response.id }}/delete/" method="get" data-ajax="false">
				<input type="hidden" name="team_id" value="{{ team.id }}">
				<input type="submit" name="delete" value="Delete Response"></input>
			</form>
		</div>
		<br></br>
	{% endfor %}
	{% endfor %}
	</fieldset>
</div>
{% endif %} <!-- if teams -->

{% endblock %}


{% block contentM %}

{% if teams %}
<div>
        <fieldset>
                <legend>Listing Challenges-Responses</legend>

        {% for team in teams %}
        {% for response in team.responses.all %}
                <p><b>Team: <a href="/gymkhana/event/{{ event.id }}/team/{{ team.id }}/show/" data-ajax="false">{{ team.group.name }} (identifier: {{ team.id }})</a></b></p>
                <p><b>- Challenge {{ response.proof.number }}</b> (identifier: {{ response.proof.id }})</p>
                <p><b>- Challenge:</b> {{ response.proof.challenge }}</p>
                <p><b>- Possible Solutions:</b></p>
                <ul>
                        {% for solution in response.proof.solution_set.all %}
                        <li>{{ solution.possible_solution }}</li>
                        {% endfor %}
                </ul>

                <p><b>- Response must be Correct to Continue:</b> {{ response.proof.is_stop }}</p>
                <p><b>- Response: {{ response.response }}</b></p>
                <p><b>- Is Correct: {{ response.is_correct }}</b></p>
                <div>
                        <form action="/gymkhana/event/{{ event.id }}/response/{{ response.id }}/edit/" method="get" data-ajax="false">
                                <input type="hidden" name="team_id" value="{{ team.id }}">
                                <input type="submit" name="change_status" value="Change to Correct/Incorrect"></input>
                        </form>
                        <form action="/gymkhana/event/{{ event.id }}/response/{{ response.id }}/delete/" method="get" data-ajax="false">
                                <input type="hidden" name="team_id" value="{{ team.id }}">
                                <input type="submit" name="delete" value="Delete Response"></input>
                        </form>
                </div>
                <br></br>
        {% endfor %}
        {% endfor %}
        </fieldset>
</div>
{% endif %} <!-- if teams -->

{% endblock %}


{% block java_script %}
<script type="text/javascript">
	//<![CDATA[
	
	function configurate(){
		// Al cargar la pagina configuramos al cliente para que
		// cada X segundos recargue la web por si hubiera nuevas respuestas 
                // de los equipos.
		// setTimeOut se ejecutaria una unica vez pasado el tiempo indicado:
		setInterval('reloadPage();',10000);
	}
	
	function createXMLHttpRequest() {
		// Obtencion del objeto XMLHttpRequest que nos permitira ejecutar
		// peticiones HTTP asincronamente desde JavaScript:
	  	var http_request = false;
 		if (window.XMLHttpRequest) { // Mozilla, Safari, ...
	 	  	http_request = new XMLHttpRequest();
		}else if (window.ActiveXObject) { // IE
		  	http_request = new ActiveXObject("Microsoft.XMLHTTP");
		}
		return http_request;
	}
	
	function reloadPage(){
		http_request = createXMLHttpRequest();
		http_request.open("GET", "/gymkhana/event/{{ event.id }}/response/list/",true);
		http_request.onreadystatechange = function() {
			if (http_request.readyState == 4) {
				if (http_request.status == 200) {
					//alert(http_request.responseText);
					var html_text = http_request.responseText;
					//var page = document.getElementById('html');
					document.getElementById('html').innerHTML = http_request.responseText;
					//insertar antes del primer elemento de pagina
					//parent.page.document.write(html_text)
					//var my_fragment = window.frames.page;
					//var doc = my_fragment.document;
				}
			}
		}
		http_request.send(null)
		// setTimeOut se ejecutaria una unica vez pasado el tiempo indicado:
		// setTimeout('loadMessages();',5000);
		// Pero ya esta puesto en el configurate() el setInterval() que se ejecuta
		// siempre cada periodo de tiempo, no solo una vez, por lo que no es
		// necesario escribir aqui esta instruccion
	}
	//]]>
</script>

{% endblock %}

apps/gymkhana/templates/list_teams.html
<!DOCTYPE html>
<html>
<head>
	<title>Gymkhana Play</title>
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Access-Control-Allow-Origin" content="*"> 
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	
	<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />

	<script type="text/javascript">
		if(typeof jQuery=='undefined'){
			document.write(unescape("<script src='jquery.mobile/jquery-1.9.1.min.js' type='text/javascript'></scri"+"pt>"));
			document.write(unescape("<script src='jquery.mobile/jquery.mobile-1.3.2.min.js' type='text/javascript'></scri"+"pt>"));
			document.write(unescape("<link rel='stylesheet' href='jquery.mobile/jquery.mobile-1.3.2.min.css' /"+">"));	
		}
	</script>

	<link href="/gymkhana/templates/css/play.css" rel="StyleSheet" />
	

	
</head>
<body>
	
	<div data-role="page" id="play">

		<div data-role="header"  data-position="fixed">
			<h1>{{ event.title }}</h1>
		</div>
		
		<br>
		<p>Seleccione el equipo con el que desea jugar.</p>
		
		<div data-role="content">
			<ul data-role="listview"  data-inset="true">

			{%for team in teams %}
			<li><a href="/gymkhana/event/{{ event.id }}/team/{{ team.id }}/start/"  data-ajax="false" id="teams"> {{ team.group }}</a></li>
			{% endfor %}
		
			</ul>
		</div>
		
		<div data-role="footer" data-position="fixed">
			<img src="/gymkhana/templates/css/images/powered_by_lgs_claro.png">
		</div>

		
	</div>

</body>
</html>